NEWTUNING = {
	MONEY_LOOT_CHANCE = 1,
	UPGRADES = {
		DAMAGE_MULT = {
			ONE = 1.25,
			TWO = 1.25,
			THREE = 1.25,
		},
		SPEED_MULT = {
			ONE = 1.25,
			TWO = 1.25,
			THREE = 1.25,
		},
		SANITY_MULT = {
			ONE = 1.25,
			TWO = 1.25,
			THREE = 1.25,
		},
		HEALTH_MULT = {
			ONE = 1.25,
			TWO = 1.25,
			THREE = 1.25,
		},
	},
	BOMB_RETRIBUTION_THRESH = 25,
	LIFE_VACUUM_REACH = 12,
	LIFE_VACUUM_NUM_SUCKS = 8,
	LIFE_VACUUM_LIFE_PERCENT_LARGE = 40,
	LIFE_VACUUM_LIFE_PERCENT_SMALL = 15,
	MINDSHAKER_USES = 25,
	WILL_HEALTH = 999,
	WILL_SANITY = 999,
	WILL_HUNGER = 999,
	WILL_HUNGER_RATE = TUNING.WILSON_HUNGER_RATE,
	WILL_DAMAGE_MULT = 2,
	WILL_DISCOUNT = 0.3,
	WILL_LOYALTY_BONUS = TUNING.TOTAL_DAY_TIME,
	WILLMOB_HEALTH = 100,
	WILLMOB_DAMAGE = 15,
}

return NEWTUNING